@Library('mcg-ci-library') _

containerAppPipeline(
    appName: 'app-laravel-kube',

    sourceRepo: 'https://github.com/princehann/app-laravel-kube.git',
    sourceBranch: 'main',

    image: 'docker.io/vhandika/perpus-laravel',

    registryHost: 'docker.io',
    registryCredentialsId: 'dockerhub-push',

    dockerfile: 'Dockerfile',
    buildContext: '.',

    // CD
    deployNamespace: 'mcg-laravel-testing',
    deploymentName: 'perpus-laravel',
    deploymentContainer: 'perpus-laravel'
)
