@Library('mcg-ci-library') _

containerAppPipeline(
    appName: 'ai-api',

    sourceRepo: 'https://github.com/princehann/app-laravel-kube.git',
    sourceBranch: 'main',
    sourceCredentialsId: 'github-repo-read',

    image: 'cr-harbor.mdka.co.id/mcgitinfra/ai-api',

    registryHost: 'cr-harbor.mdka.co.id',
    registryCredentialsId: 'harbor-push',

    dockerfile: 'Dockerfile',
    buildContext: '.',

    // CD
    deployNamespace: 'mcg-laravel',
    deploymentName: 'ai-api',
    deploymentContainer: 'php84-10'
)

